
model:
  posterior_kwargs:
    hidden_dim: 128
    depth: 6
    heads: 4
    context_num_tokens: 4
    theta_num_tokens: 2
    is_individual: false
    time_prior_exponent: 4
    sigma_min: 0.0001
    type: mmdit
    repeated_batch_size: 16
    euler_steps: 200
  type: flow_matching_aug
task:
  name: two_moons
  # Other options: bernoulli_glm, bernoulli_glm_raw, gaussian_linear, gaussian_linear_uniform, gaussian_mixture, lotka_volterra, sir, slcp, slcp_distractors, two_moons
  num_train_samples: 100000
training:
  device: cuda
  batch_size: 512
  early_stopping: false
  epochs: 50
  num_workers: 0
  optimizer:
    lr: 0.0002
    type: adam
  scheduler:
    T_max: 50
    eta_min: 0.000001
    type: cosine
  train_fraction: 0.95
